# Build Docker image with CI/CD and push to the GitLab registry.

variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_USER -p $CI_PASSWORD $LOCAL_REGISTRY
headwater-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd headwater
    - docker build -t $CI_REGISTRY/headwater:stable . --network=host
    - docker push $CI_REGISTRY/headwater:stable
base-build:
  tags: [build]
  stage: build
  needs: [headwater-build]
  script:
    - cd base/cpu
    - docker build -t $CI_REGISTRY/base:cpu . --network=host
    - docker push $CI_REGISTRY/base:cpu
deeplearning-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd deeplearning/cpu
    - docker build -t $CI_REGISTRY/deeplearning:cpu . --network=host
    - docker push $CI_REGISTRY/deeplearning:cpu
datascience-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd datascience/cpu
    - docker build -t $CI_REGISTRY/datascience:cpu . --network=host
    - docker push $CI_REGISTRY/datascience:cpu
