# Build Docker image with CI/CD and push to the GitLab registry.

variables:
  IMAGEHUB: "eoelab.org:1032"
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $IMAGEHUB
upstream-build:
  tags: [build]
  stage: build
  script:
    - cd headwater
    - docker build -t $CI_REGISTRY/headwater:stable . --network=host
    - docker push $CI_REGISTRY/headwater:stable
base-build:
  tags: [build]
  stage: build
  script:
    - cd headwater
    - docker build -t $CI_REGISTRY/base:stable . --network=host
    - docker push $CI_REGISTRY/base:stable
scipy-build:
  tags: [build]
  stage: build
  script:
    - cd headwater
    - docker build -t $CI_REGISTRY/scipy:stable . --network=host
    - docker push $CI_REGISTRY/scipy:stable