# Build Docker image with CI/CD and push to the GitLab registry.
variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_USER -p $CI_PASSWORD $LOCAL_REGISTRY
up-c-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/cpu
    - docker build -t $CI_REGISTRY/jupyter:up-c . --network=host
base-c-build:
  tags: [build]
  stage: build
  needs: [up-c-build]
  script:
    - cd base/cpu
    - docker build -t $CI_REGISTRY/jupyter:base-c . --network=host
    - docker push $CI_REGISTRY/jupyter:base-c
scipy-c-build:
  tags: [build]
  stage: build
  needs: [base-c-build]
  script:
    - cd scipy/cpu
    - docker build -t $CI_REGISTRY/jupyter:scipy-c . --network=host
    - docker cpph $CI_REGISTRY/jupyter:scipy-c
cpp-c-build:
  tags: [build]
  stage: build
  needs: [base-c-build]
  script:
    - cd cpp
    - docker build -t $CI_REGISTRY/jupyter:cpp-c . --network=host
    - docker push $CI_REGISTRY/jupyter:cpp-c
julia-c-build:
  tags: [build]
  stage: build
  needs: [base-c-build]
  script:
    - cd julia
    - docker build -t $CI_REGISTRY/jupyter:julia-c . --network=host
    - docker push $CI_REGISTRY/jupyter:julia-c
r-c-build:
  tags: [build]
  stage: build
  needs: [base-c-build]
  script:
    - cd r
    - docker build -t $CI_REGISTRY/jupyter:r-c . --network=host
    - docker push $CI_REGISTRY/jupyter:r-c
sage-c-build:
  tags: [build]
  stage: build
  needs: [base-c-build]
  script:
    - cd sagemath
    - docker build -t $CI_REGISTRY/jupyter:sage-c . --network=host
    - docker push $CI_REGISTRY/jupyter:sage-c
dl-c-build:
  tags: [build]
  stage: build
  needs: [scipy-c-build]
  script:
    - cd deeplearning/cpu
    - docker build -t $CI_REGISTRY/jupyter:dl-c . --network=host
    - docker push $CI_REGISTRY/jupyter:dl-c
up-g-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/gpu
    - docker build -t $CI_REGISTRY/jupyter:up-g . --network=host
base-g-build:
  tags: [build]
  stage: build
  needs: [up-g-build]
  script:
    - cd base/gpu
    - docker build -t $CI_REGISTRY/jupyter:base-g . --network=host
scipy-g-build:
  tags: [build]
  stage: build
  needs: [base-g-build]
  script:
    - cd scipy/gpu
    - docker build -t $CI_REGISTRY/jupyter:scipy-g . --network=host
dl-g-build:
  tags: [build]
  stage: build
  needs: [scipy-g-build]
  script:
    - cd deeplearning/gpu
    - docker build -t $CI_REGISTRY/jupyter:dl-g . --network=host
    - docker push $CI_REGISTRY/jupyter:dl-g
