# Build Docker image with CI/CD and push to the GitLab registry.
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
before_script:
  - wget https://eoelab.org:1024/index.php/s/ac3eQY4byy4mK2g/download/eoelab.org.crt
  - mv eoelab.org.crt /kaniko/ssl/certs/additional-ca-cert-bundle.crt
qsharp-build:
  stage: build
  needs: []
  script:
    - cd qsharp
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=false
      --snapshot-mode=redo
      --cache-repo "eoelab.org:1032/build-image-stacks/jupyter-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/jupyter-image-stacks/jupyter:qsharp-c"