# Build Docker image with CI/CD and push to the GitLab registry.
image: docker:stable
services:
  - docker:dind
variables:
  CI_REGISTRY: "eoelab.org:1032"
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
base-build:
  tags: [com]
  stage: build
  script:
    - cd base
    - docker build -t $CI_REGISTRY/base:stable . --network=host
    - docker push $CI_REGISTRY_IMAGE/base:stable
