# Build Docker image with CI/CD and push to the GitLab registry.
image: docker:latest
services:
  - docker:dind
variables:

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD eoelab.org:1032
base-build:
  tags: [build]
  stage: build
  script:
    - cd base
    - docker build -t eoelab.org:1032/base:stable . --network=host
    - docker push eoelab.org:1032/base:stable
