# Build Docker image with CI/CD and push to the GitLab registry.
variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"

up-c-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/cpu
    - docker build -t $CI_REGISTRY/jupyter:up-c . --network=host
up-g-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/gpu
    - docker build -t $CI_REGISTRY/jupyter:up-g . --network=host

