# Build Docker image with CI/CD and push to the GitLab registry.
variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"

sage-c-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd sagemath
    - docker build -t $CI_REGISTRY/jupyter:sage-c . --network=host
