# Build Docker image with CI/CD and push to the GitLab registry.
test-build:
  tags: [build]
  stage: test
  needs: []
  script:
    - cd upstream/cpu
    - docker build -t eoelab.org:1032/build-image-stacks/jupyter-image-stacks/jupyter:up-test . --network=host
