# Build Docker image with CI/CD and push to the GitLab registry.

variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_USER -p $CI_PASSWORD $LOCAL_REGISTRY
up-cpu-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/cpu
    - docker build -t $CI_REGISTRY/jupyter:up-c . --network=host
    - docker push $CI_REGISTRY/jupyter:up-c
up-gpu-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/gpu
    - docker build -t $CI_REGISTRY/jupyter:up-g . --network=host
    - docker push $CI_REGISTRY/jupyter:up-g
base-build:
  tags: [build]
  stage: build
  needs: [up-cpu-build]
  script:
    - cd base
    - docker build -t $CI_REGISTRY/jupyter:base . --network=host
    - docker push $CI_REGISTRY/jupyter:base
sage-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd sage
    - docker build -t $CI_REGISTRY/jupyter:sage . --network=host
    - docker push $CI_REGISTRY/jupyter:sage
scipy-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd scipy
    - docker build -t $CI_REGISTRY/jupyter:scipy . --network=host
    - docker push $CI_REGISTRY/jupyter:scipy
deeplearning-build:
  tags: [build]
  stage: build
  needs: [scipy-build]
  script:
    - cd deeplearning/cpu
    - docker build -t $CI_REGISTRY/jupyter:dl-c . --network=host
    - docker push $CI_REGISTRY/jupyter:dl-c
datascience-build:
  tags: [build]
  stage: build
  needs: [scipy-build]
  script:
    - cd datascience/cpu
    - docker build -t $CI_REGISTRY/jupyter:data-c . --network=host
    - docker push $CI_REGISTRY/jupyter:data-c
