# Build Docker image with CI/CD and push to the GitLab registry.

variables:
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_USER -p $CI_PASSWORD $LOCAL_REGISTRY
upstream-c-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd upstream/upstream-cpu
    - docker build -t $CI_REGISTRY/jupyter:up-c . --network=host
    - docker push $CI_REGISTRY/jupyter:up-c
base-build:
  tags: [build]
  stage: build
  needs: [upstream-c-build]
  script:
    - cd base
    - docker build -t $CI_REGISTRY/jupyter:base . --network=host
    - docker push $CI_REGISTRY/jupyter:base
deeplearning-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd deeplearning/cpu
    - docker build -t $CI_REGISTRY/jupyter:dl-c . --network=host
    - docker push $CI_REGISTRY/jupyter:dl-c
datascience-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd datascience/cpu
    - docker build -t $CI_REGISTRY/jupyter:data-c . --network=host
    - docker push $CI_REGISTRY/jupyter:data-c
