# Build Docker image with CI/CD and push to the GitLab registry.

variables:
  IMAGEHUB: "eoelab.org:1032"
  CI_REGISTRY: "eoelab.org:1032/build-image-stacks/jupyter-image-stacks"
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $IMAGEHUB
headwater-build:
  tags: [build]
  stage: build
  needs: []
  script:
    - cd headwater
    - docker build -t $CI_REGISTRY/headwater:stable . --network=host
    - docker push $CI_REGISTRY/headwater:stable
base-build:
  tags: [build]
  stage: build
  needs: [headwater-build]
  script:
    - cd base
    - docker build -t $CI_REGISTRY/base:stable . --network=host
    - docker push $CI_REGISTRY/base:stable
deeplearning-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd deeplearning
    - docker build -t $CI_REGISTRY/deeplearning:stable . --network=host
    - docker push $CI_REGISTRY/deeplearning:stable
datascience-build:
  tags: [build]
  stage: build
  needs: [base-build]
  script:
    - cd datascience
    - docker build -t $CI_REGISTRY/datascience:stable . --network=host
    - docker push $CI_REGISTRY/datascience:stable
